stages: [compile, run, test]

run_compile_iimpi2024:
    image: gitlab-registry.mpcdf.mpg.de/mpcdf/ci-module-image/intel_2024_0-impi_2021_11:2024
    stage: compile
    tags:
        - cloud
    before_script:
        - module load intel/2024.0 impi/2021.11 hdf5-mpi
    script:
        - make FC=mpiifort
    artifacts:
        paths:
            - test_h5

run_run_iimpi2024:
    image: gitlab-registry.mpcdf.mpg.de/mpcdf/ci-module-image/intel_2024_0-impi_2021_11:2024
    stage: run
    tags:
        - cloud
    before_script:
        - module load intel/2024.0 impi/2021.11 hdf5-mpi
    script:
        - make run2
    artifacts:
        paths:
            - fast.h5

run_test_iimpi2024:
    image: gitlab-registry.mpcdf.mpg.de/mpcdf/ci-module-image/intel_2024_0-impi_2021_11:2024
    stage: test
    tags:
        - cloud
    before_script:
        - module load intel/2024.0 impi/2021.11 hdf5-mpi
    script:
        - h5ls -r fast.h5
        - h5dump -d /ID_PIC fast.h5
        - h5dump -d /S_PIC fast.h5

run_testpy_iimpi2024:
    image: gitlab-registry.mpcdf.mpg.de/mpcdf/ci-module-image/intel_2024_0-impi_2021_11:2024
    stage: test
    tags:
        - cloud
    before_script:
        - module load anaconda/3/2023.03
    script:
        - python test_id.py
